apiVersion: v2
kind: Service
metadata:
  namespace: optit-lab
  name: react-app-service
spec:
  selector:
    app: react-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer